apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpc-app-sa
  namespace: proxyless
  annotations:
    # Workload Identity: this KSA impersonates the GSA that holds
    # roles/trafficdirector.client (created by Terraform).
    iam.gke.io/gcp-service-account: grpc-mesh-app@proxyless-grpc-mesh.iam.gserviceaccount.com
